### ISSUE TITLE
设备影子无法同时使用设备日志功能

### ISSUE THREAD

**Issue by wxiaowen** [tencentyun/iot-device-java#12]
![1640699635(1)](https://user-images.githubusercontent.com/32184142/147573278-9516ae65-98f5-4ece-8803-ec010c05adfd.png)
源码中没有设置TXMqttConnection的mMqttLogFlag，所以导致mMqttLog一直为null,希望帮解决更新下！！

**Comment by archurcode** [comment]
> ![1640699635(1)](https://user-images.githubusercontent.com/32184142/147573278-9516ae65-98f5-4ece-8803-ec010c05adfd.png) 源码中没有设置TXMqttConnection的mMqttLogFlag，所以导致mMqttLog一直为null,希望帮解决更新下！！

好的，今天会更新哈
