### ISSUE TITLE
频繁上下线

### ISSUE THREAD

**Issue by wave-chtj** [tencentyun/iot-device-java#2]
网络连接状态下，把网线拔掉，或者4G掉线了，物联网平台显示离线之后，再恢复网络，这时候就会频繁上下线

**Comment by SundoggyNew** [comment]
> 网络连接状态下，把网线拔掉，或者4G掉线了，物联网平台显示离线之后，再恢复网络，这时候就会频繁上下线

物联网接入层有设备互踢的逻辑，如果是用同一个设备 ID 在不同地方登录，会导致其中一方被另一方踢下线。因此发现设备一直上下线时，劳烦确认下是否有不同的人或者多线程在使用同一个设备 ID 执行登录操作。

**Comment by wave-chtj** [comment]
测试条件如下：刚开正常上线，查看平台在线后，拔掉网线，等待平台反馈离线，然后再插上网线，这个问题就出现了

**Comment by SundoggyNew** [comment]
> 测试条件如下：刚开正常上线，查看平台在线后，拔掉网线，等待平台反馈离线，然后再插上网线，这个问题就出现了

请问你使用的哪一款SDK，hub-device-android，hub-device-java，explorer-device-android，explorer-device-java。我在hub-device-android中没有遇到这个问题，可以排查下在控制台重新创建一个产品设备会不会还遇到这个问题。
