### ISSUE TITLE
use IoT Hub Android-SDK can't import in the app

### ISSUE THREAD

**Issue by jjamyang** [tencentyun/iot-device-java#20]
Hello tencent,
我按照这个指引:
https://github.com/tencentyun/iot-device-java/blob/master/hub/hub-device-android/docs/zh/%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83%E5%8F%8ASDK%E6%8E%A5%E5%85%A5%E8%AF%B4%E6%98%8E.md
提到的方式:
gradle 工程正式版 SDK 远程构建

在应用模块的 build.gradle 中配置，具体版本号可参考 [Latest release](https://github.com/tencentyun/iot-device-java/releases) 版本

dependencies {
    implementation 'com.tencent.iot.hub:hub-device-android:3.3.21'
}

可以编译过;

但是想引用API的时候 import会提示失败;
![屏幕截图 2023-04-23 225023](https://user-images.githubusercontent.com/17903822/233847008-221a246a-fe89-4d7d-847b-cfb8f72e90a6.png)

>>> 问题: 除了APP部分的Setting.gradle填写上述指引的部分, 这个SDK的引用还需要设置其他地方吗？

**Comment by SundoggyNew** [comment]
请clean project，清除一下.gradle缓存，Invalidate Caches / Restart，重新拉取一下工程依赖。
<img width="513" alt="image" src="https://user-images.githubusercontent.com/16092720/236097670-179eda0b-dc78-462d-bbe5-37e9733d8b64.png">

**Comment by jjamyang** [comment]
Hi Tencent~
按照您的指引解决了"Invalidate Caches / Restart，重新拉取一下工程依赖"; 

感谢支援
