### ISSUE TITLE
等待平台反馈离线，周期太久，大概在5-10分钟才会判断离线

### ISSUE THREAD

**Issue by wave-chtj** [tencentyun/iot-device-java#3]
起因是我没有关闭连接，而这个时候网络异常了，平台反应时间太久，这对于测试上下线问题不及时

**Comment by SundoggyNew** [comment]
> 起因是我没有关闭连接，而这个时候网络异常了，平台反应时间太久，这对于测试上下线问题不及时

当网络断开异常时，设备不会立刻被判断为离线状态，mqtt客户端超过一定时间仍没收到心跳响应，才被判断为断开连接，离线的状态。
