### ISSUE TITLE
怎么拉取不下来

### ISSUE THREAD

**Issue by tony-lu-neng** [tencentyun/iot-device-java#4]
Cloning into 'hub-device-java'...
fatal: repository 'https://github.com/tencentyun/iot-device-java/tree/master/hub-device-java/' not found

**Comment by SundoggyNew** [comment]
> Cloning into 'hub-device-java'...
> fatal: repository 'https://github.com/tencentyun/iot-device-java/tree/master/hub-device-java/' not found

您可以尝试拉取整个代码库的代码。git clone https://github.com/tencentyun/iot-device-java.git
