### ISSUE TITLE
不同的应有用同一个sdk会导致消息混乱吗

### ISSUE THREAD

**Issue by wave-chtj** [tencentyun/iot-device-java#5]
hi ，之前公司android设备上用了这个iot sdk(Cloud应用),客户自己也开发了一个应用(应该是用到了同一个sdk),导致客户的程序受到影响，具体表现为网络隔一段时间刷新了客户的应用程序，除此之外没什么其他异常，现在我们的应用无法和客户的应用共存，这对我们来说很重要,这个mqtt服务在设备固有参数不变的情况下，存在了这样的问题，经过了多次测试

**Comment by archurcode** [comment]
您好，请问贵公司使用的是哪一个sdk呢？hub-device-android还是explorer-device-android

**Comment by SundoggyNew** [comment]
> hi ，之前公司android设备上用了这个iot sdk(Cloud应用),客户自己也开发了一个应用(应该是用到了同一个sdk),导致客户的程序受到影响，具体表现为网络隔一段时间刷新了客户的应用程序，除此之外没什么其他异常，现在我们的应用无法和客户的应用共存，这对我们来说很重要,这个mqtt服务在设备固有参数不变的情况下，存在了这样的问题，经过了多次测试

网络隔一段时间刷新了客户的应用程序，是否是收到了下发Topic消息时刷新的，这里建议判断一下是自己订阅的Topic的消息才做对应业务上的刷新处理。

**Comment by wave-chtj** [comment]
> 您好，请问贵公司使用的是哪一个sdk呢？hub-device-android还是explorer-device-android

hub-device-android

**Comment by wave-chtj** [comment]
> > hi ，之前公司android设备上用了这个iot sdk(Cloud应用),客户自己也开发了一个应用(应该是用到了同一个sdk),导致客户的程序受到影响，具体表现为网络隔一段时间刷新了客户的应用程序，除此之外没什么其他异常，现在我们的应用无法和客户的应用共存，这对我们来说很重要,这个mqtt服务在设备固有参数不变的情况下，存在了这样的问题，经过了多次测试
> 
> 网络隔一段时间刷新了客户的应用程序，是否是收到了下发Topic消息时刷新的，这里建议判断一下是自己订阅的Topic的消息才做对应业务上的刷新处理。

客户自己开发的程序我不清楚 我这里呢也可以去做这个topic的区分，但是基于这个协议，我不可能去干涉别人的topic吧，如果他一直保持现在topic，没有对其他topic进行区分，那么我改了，似乎也没什么用，因为每个应用对自己的tipic进行处理

**Comment by archurcode** [comment]
> > > hi ，之前公司android设备上用了这个iot sdk(Cloud应用),客户自己也开发了一个应用(应该是用到了同一个sdk),导致客户的程序受到影响，具体表现为网络隔一段时间刷新了客户的应用程序，除此之外没什么其他异常，现在我们的应用无法和客户的应用共存，这对我们来说很重要,这个mqtt服务在设备固有参数不变的情况下，存在了这样的问题，经过了多次测试
> > 
> > 
> > 网络隔一段时间刷新了客户的应用程序，是否是收到了下发Topic消息时刷新的，这里建议判断一下是自己订阅的Topic的消息才做对应业务上的刷新处理。
> 
> 客户自己开发的程序我不清楚 我这里呢也定义了一个topic，但是基于这个协议，我不可能去干涉别人的topic吧，如果他一直保持现在topic，没有对其他topic进行区分，那么我改了，似乎也没什么用，因为每个应用应该对自己的tipic进行处理，不处理别人的

有没有可能是客户订阅了你们的topic
